### ISSUE TITLE
`Could not find com.kyonifer:koma-core-ejml` due to bintray shutdown

### ISSUE THREAD

**Issue by MarkTheHopeful** [kyonifer/koma#107]
Since 2021-05-01 all bintray services are down permanently, therefore it's impossible to use bintray-hosted libraries. Is it possible to migrate it somewhere? For example, to repo.kotlin.link ?

**Comment by brianbolze** [comment]
Please help!

**Comment by brianbolze** [comment]
Has anyone tried migrating this themselves? Or importing this as a source dependency in Gradle? We’ve had no luck so far and this is blocking an Android release for us.

**Comment by brianbolze** [comment]
My team is considering replacing this with KMath (https://github.com/mipt-npm/kmath) if we don’t hear back soon.

**Comment by venabled** [comment]
The kmath library you linked looks pretty actively developed and maintained. I'm not sure @kyonifer and the team here have had much time / use case to add features or even maintenance releases for koma lately, unfortunately

**Comment by brianbolze** [comment]
Yup. I’d be willing to help contribute to make Koma work, but the
dependency structure with the backend implementations like EJML and setting
up a repo on Maven would take me a while given my current skillset.

Sent via Superhuman iOS ***@***.***>

**Comment by brianbolze** [comment]
After further review, it looks like even KMath might suffer from the same
issue since it's ejml-matrix module also relies on Bintray [image: 😔]

Has anyone else found any workarounds for this?

Sent via Superhuman ***@***.***>

**Comment by brianbolze** [comment]
I'm looking at the open-source EJML code [here](https://github.com/lessthanoptimal/ejml). It says it's on the Maven Central Repository. Could we just modify the Gradle dependency structure in this project to point to there instead of bintray?

**Comment by venabled** [comment]
If you have a local cache of the thing you can self host the artifact or try GitHub packages which supports Maven/Gradle

**Comment by Das-dasein** [comment]
Very thanks, you broke my thesis 👍🏿 👍🏿 👍🏿 👍🏿 👍🏿 👍🏿 👍🏿 👍🏿

**Comment by RinkiBEtheridge** [comment]
@Das-dasein : How did you get this to work? My local cache has jar and pom files. I am sorry I don't know much about maven/gradle.

**Comment by kyonifer** [comment]
Closing this issue for now, as the script in [this comment](https://github.com/kyonifer/koma/pull/108#issuecomment-837254292) appears to work with the github hosted artifacts.
