### ISSUE TITLE
Forbidden from maven repo url 

### ISSUE THREAD

**Issue by Millad** [kyonifer/koma#110]
I followed the instruction on your site for quick start with gradle. I added the maven repo url but get forbidden when downloading koma core api...

**Comment by drmoose** [comment]
Bintray no longer exists. See #108 for new gradle dependencies.

**Comment by Millad** [comment]
Hello again @drmoose,

I have tried the following without luck.

`plugins {
    id("java")
    id("org.jetbrains.kotlin.jvm") version "1.3.72"
    id("io.github.0ffz.github-packages") version "1.2.1"
    application
}

repositories {
    mavenCentral()
    jcenter()
    githubPackage("kyonifer")
    maven { url = uri("https://plugins.gradle.org/m2/") }
}

dependencies {
    implementation("com.kyonifer:koma-core-ejml:0.12")
}
`
It still cannot fint the dependency

**Comment by drmoose** [comment]
The `jcenter` line needs to be removed entirely; jcenter has been deleted.

You also appear to be missing a `buildscript` block. At a minimum, the following is necessary for the github-packages plugin to work:

```
buildscript {
  repositories {
    maven { url "https://plugins.gradle.org/m2/" }
    mavenCentral()
  }
}
```

**Comment by Millad** [comment]
`
  buildscript {
    repositories {
        mavenCentral()
        jcenter()
        githubPackage("kyonifer")
        maven { url =uri("https://jitpack.io")  }
        maven { url = uri("https://plugins.gradle.org/m2/") }
    }
}

dependencies {
    implementation("com.kyonifer:koma-core-ejml:0.12.1")
`

says :
Line 11:         githubPackage("kyonifer")
                   ^ Unresolved reference: githubPackage

**Comment by Millad** [comment]
My repo: https://github.com/Millad/Convolutional-neural-network-without-frameworks-in-kotlin

**Comment by drmoose** [comment]
:arrow_up: I opened that pull request on your repo. Each commit message should show what I did and why.

**Comment by Millad** [comment]
thanks, i would have never guessed the githubPackage() this() method.
