### ISSUE TITLE
EJML matrix decomp failing

### ISSUE THREAD

**Issue by RatsRatsRats** [kyonifer/koma#33]
Attempting to use something like eye(2).QR() always seems to result in empty matrices being returned for QR when using EJML backend (not tested on others). It appears that a call to 

`decomp.decompose(this.storage.matrix)`

after [this line](https://github.com/kyonifer/koma/blob/master/backend-matrix-ejml/src/koma.matrix.ejml/EJMLMatrix.kt#L119) may help following docs for `getQ()` [here](http://ejml.org/javadoc/org/ejml/interfaces/decomposition/QRDecomposition.html).

**Comment by kyonifer** [comment]
Thanks for reporting.
