### ISSUE TITLE
Correction Needed on Web Site About KLib

### ISSUE THREAD

**Issue by quenio** [kyonifer/koma#62]
This page on the web site:
https://koma.kyonifer.com/General_Usage_Guide/Advanced/Build_From_Source/index.html

Says the following command generates the KLib:

```
./gradlew compileKonanKoma -Ptarget=native
```

But the right command is:

```
./gradlew compileKonanKomaKLib -Ptarget=native
```

Just need to replace `compileKonanKoma` with `compileKonanKomaKLib`.

**Comment by kyonifer** [comment]
Thanks for the report. Subtask of #54. Among other things `-Ptarget=native` also doesn't exist anymore on master, and there's some convenience tasks defined like `buildNative` that the docs don't mention.

I'm planning on trying out the new k/native gradle DSL and trying to push some native maven artifacts again before doing a clean pass through the build docs to update everything.
