### ISSUE TITLE
Plotting Not Available for Kotlin Native

### ISSUE THREAD

**Issue by quenio** [kyonifer/koma#64]
It seems Plotting is not available with Kotlin Native.

I'd put a note about that [here](https://koma.kyonifer.com/General_Usage_Guide/Plotting/index.html) and [here](https://koma.kyonifer.com/index.html#quickstart-native).

**Comment by kyonifer** [comment]
Closed by 60a0780522653b860c2d660f3ef0d38573e2cb26.
