### ISSUE TITLE
How to compile plotting library?

### ISSUE THREAD

**Issue by peastman** [kyonifer/koma#67]
Sorry if this is a bit of a beginner question.  I'm trying to compile Koma from source.  Following the instructions, I run

```
./gradlew buildJvm
```

That produces jar files for `koma-core-api-jvm`, `koma-core-ejml`, `koma-core-jblas`, and `koma-core-mtj`.  But none of those contains the plotting functions.  I'm new to Gradle, but I looked through the build script and found the block

```
task buildJvm {
    dependsOn(":koma-core-mtj:build")
    dependsOn(":koma-core-ejml:build")
    dependsOn(":koma-core-jblas:build")
    dependsOn(":koma-core-api-jvm:build")
}
```

I don't see any task that depends on `:koma-plotting`.  How do I compile that?

**Comment by kyonifer** [comment]
You're right, I forgot some projects in `buildJvm`. For now, you can run `./gradlew koma-plotting:build` to create `koma-plotting-0.12.jar` in `build/jvm`. I'll fix the `buildJvm` task soon.

**Comment by peastman** [comment]
Thanks!  Works perfectly.
